version: 2
updates:
  - package-ecosystem: 'npm'
    open-pull-requests-limit: 5
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore'
    assignees:
      - 'tataihono'
    reviewers:
      - 'tataihono'
    labels:
      - 'type: chore'
