kind: Deployment
apiVersion: apps/v1
metadata:
  name: snapshot-controller
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snapshot-controller
  minReadySeconds: 15
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: snapshot-controller
    spec:
      serviceAccountName: snapshot-controller
      containers:
        - name: snapshot-controller
          image: registry.k8s.io/sig-storage/snapshot-controller:v6.2.1
          args:
            - '--v=5'
            - '--leader-election=true'
          imagePullPolicy: IfNotPresent
