apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds/volumesnapshotclasses.snapshot.storage.k8s.io.yaml
  - crds/volumesnapshotcontents.snapshot.storage.k8s.io.yaml
  - crds/volumesnapshots.snapshot.storage.k8s.io.yaml
  - rbac-snapshot-controller.yaml
  - deployment-snapshot-controller.yaml
