clusterName: jfp-eks-prod
site: datadoghq.com
containerStrategy: single
credentials:
  apiSecret:
    secretName: datadog-secret
    keyName: api-key
logs:
  enabled: true
  containerCollectAll: true
clusterChecks:
  enabled: true
