apiVersion: v2
name: external-dns-app
description: Wrapper chart for external-dns managed by ArgoCD
type: application
version: 0.1.0
appVersion: '0.15.0'

dependencies:
  - name: external-dns
    version: 1.15.0
    repository: https://kubernetes-sigs.github.io/external-dns/
