apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-journeys-main
  labels:
    app: api-journeys-main
    type: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-journeys-main
  template:
    metadata:
      labels:
        app: api-journeys-main
    spec:
      containers:
        - image: 894231352815.dkr.ecr.us-east-2.amazonaws.com/jfp-api-journeys:main
          imagePullPolicy: IfNotPresent
          name: jfp-api-journeys
          envFrom:
            - secretRef:
                name: env-db-main
          ports:
            - containerPort: 4001
