apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-stage
  labels:
    app: api-gateway-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-stage
  template:
    metadata:
      labels:
        app: api-gateway-stage
    spec:
      containers:
        - image: 894231352815.dkr.ecr.us-east-2.amazonaws.com/jfp-api-gateway:stage
          imagePullPolicy: IfNotPresent
          name: jfp-api-gateway
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: env-firebase-stage
            - secretRef:
                name: env-apollo-gateway-stage
