apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-users-main
  labels:
    app: api-users-main
    type: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-users-main
  template:
    metadata:
      labels:
        app: api-users-main
    spec:
      containers:
      - image: 894231352815.dkr.ecr.us-east-2.amazonaws.com/jfp-api-users:c33fe910f485803718fa8d656d85816755247078
        imagePullPolicy: IfNotPresent
        name: jfp-api-users
        ports:
          - containerPort: 4002
        envFrom:
        - secretRef:
            name: env-db-main
---
apiVersion: v1
kind: Service
metadata:
  name: api-users-main
spec:
  selector:
    app: api-users-main
  ports:
    - port: 4002
  type: LoadBalancer  
