apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-main
  labels:
    app: api-gateway-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-main
  template:
    metadata:
      labels:
        app: api-gateway-main
    spec:
      containers:
      - image: 894231352815.dkr.ecr.us-east-2.amazonaws.com/jfp-api-gateway:c33fe910f485803718fa8d656d85816755247078
        imagePullPolicy: IfNotPresent
        name: jfp-api-gateway
        ports:
          - containerPort: 4000
        envFrom:
        - secretRef:
            name: env-firebase-main          
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-main
spec:
  selector:
    app: api-gateway-main
  ports:
    - port: 4000
  type: LoadBalancer