apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-stage
  labels:
    app: api-gateway-stage
    type: api
  annotations:
    secrets.doppler.com/reload: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-stage
  template:
    metadata:
      labels:
        app: api-gateway-stage
    spec:
      nodeSelector:
        type: api
      containers:
        - image: 894231352815.dkr.ecr.us-east-2.amazonaws.com/jfp-api-gateway-stage:latest
          imagePullPolicy: IfNotPresent
          name: jfp-api-gateway
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: doppler-api-gateway-secret-stg
