apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-languages-stage
  labels:
    app: api-languages-stage
    type: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-languages-stage
  template:
    metadata:
      labels:
        app: api-languages-stage
    spec:
      containers:
        - image: 894231352815.dkr.ecr.us-east-2.amazonaws.com/jfp-api-languages:stage
          imagePullPolicy: IfNotPresent
          name: jfp-api-languages
          envFrom:
            - secretRef:
                name: env-db-stage
            - secretRef:
                name: env-arclight
          ports:
            - containerPort: 4003
